blueprint:
  name: Chen Doorbell notification and Snapshot
  description: 'This automation blueprint creates a camera snapshot if doorbell button
    is pressed  and sends a notification to your phone with the picture.

    '
  domain: automation
  input:
    motion_sensor:
      name: Doorbell
      description: The sensor wich triggers the snapshot creation
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    camera:
      name: Camera
      description: The camera which creates the snapshot
      selector:
        entity:
          domain:
          - camera
          multiple: false
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive
        notifications
      selector:
        device:
          integration: mobile_app
          multiple: false
    is_ios:
      name: Is it an iOS device?
      description: Toggle if your selected device runs iOS, default is Android
      selector:
        boolean: {}
      default: false
    notification_title:
      name: Notification title (Optional)
      description: Doorbell
      default: Doorbell
    notification_message:
      name: Notification message (Optional)
      description: Someones at the door
      default: Someones at the door
    delay:
      name: Delay (Optional)
      description: Wait before creating camera snapshot
      default: 0
      selector:
        number:
          min: 0.0
          max: 60.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
  source_url: https://github.com/hanm13/home-assistant/blob/main/blueprints/doorbell_notification_snapshot/chen_doorbell_notification.yml
trigger:
  platform: state
  entity_id: !input motion_sensor
variables:
  motion_sensor: !input motion_sensor
  motion_sensor_name: '{{ states[motion_sensor].name }}'
  camera: !input camera
  notify_device: !input notify_device
  is_ios: !input is_ios
  notification_title: !input notification_title
  notification_message: !input notification_message
  delay: !input delay
  snapshot_create_file_path: /config/www/tmp/snapshot_{{ states[camera].object_id
    }}_{{ now().strftime("%Y.%m.%d-%H.%M.%S") }}.jpg
  snapshot_access_file_path: '{{ snapshot_create_file_path | replace(''/config/www'',''/local'')
    }}'
action:
- delay: '{{ delay }}'
- service: camera.snapshot
  entity_id: !input camera
  data:
    filename: '{{ snapshot_create_file_path }}'
- device_id: !input notify_device
  domain: mobile_app
  type: notify
  title: '{{ notification_title }}'
  message: '{{ notification_message }}'
  data: '{% set android_data = {"ttl":0,"priority":"high","channel":"doorbell","image":
    "%s"} | format(snapshot_access_file_path) %} {% set ios_data = {"attachment":
    {"url": "%s", "content_type": "JPEG"}} | format(snapshot_access_file_path) %}
    {{ ios_data if is_ios else android_data }}'
