blueprint:
  name: Chen Doorbell smartphone notification and Snapshot
  description: 'This automation blueprint creates a camera snapshot if doorbell button
    is pressed  and sends a notification to your phone with the picture + home assistant if enabled.

    '
  domain: automation
  input:
    motion_sensor:
      name: Doorbell
      description: The sensor which triggers the snapshot creation
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    camera:
      name: Camera
      description: The camera which creates the snapshot
      selector:
        entity:
          domain:
          - camera
          multiple: false
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive
        notifications
      selector:
        device:
          integration: mobile_app
          multiple: false
    is_ios:
      name: Is it an iOS device?
      description: Toggle if your selected device runs iOS, default is Android
      selector:
        boolean: {}
      default: false
    enable_homeassistant_notification:
      name: Enable homeassistant notification?
      description: Enable homeassistant notification?
      selector:
        boolean: {}
      default: false
    enable_smartphone_notification:
      name: Enable smartphone notification?
      description: Enable smartphone notification?
      selector:
        boolean: {}
      default: false
    notification_title:
      name: Notification title (Optional)
      description: Doorbell
      default: Doorbell
    notification_message:
      name: Notification message (Optional)
      description: Someones at the door
      default: Someones at the door
    delay:
      name: Delay (Optional)
      description: Wait before creating camera snapshot
      default: 0
      selector:
        number:
          min: 0.0
          max: 60.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
  source_url: https://github.com/hanm13/home-assistant/blob/main/blueprints/doorbell_notification_snapshot/chen_doorbell_notification.yml
trigger:
  platform: state
  entity_id: !input motion_sensor
variables:
  motion_sensor: !input motion_sensor
  motion_sensor_name: '{{ states[motion_sensor].name }}'
  camera: !input camera
  notify_device: !input notify_device
  is_ios: !input is_ios
  enable_homeassistant_notification: !input enable_homeassistant_notification
  enable_smartphone_notification: !input enable_smartphone_notification
  notification_title: !input notification_title
  notification_message: !input notification_message
  delay: !input delay
  snapshot_create_file_path: /config/www/tmp/snapshot_{{ states[camera].object_id
    }}_{{ now().strftime("%d.%m.%Y-%H.%M.%S") }}.jpg
  snapshot_access_file_path: '{{ snapshot_create_file_path | replace(''/config/www'',''/local'')
    }}'
action:
- delay: '{{ delay }}'
- service: notify.persistent_notification
  enabled: !input enable_homeassistant_notification
  data:
    message: <b>{{ notification_message }} ![Garage Motion]({{ snapshot_access_file_path }})
- service: camera.snapshot
  entity_id: !input camera
  data:
    filename: '{{ snapshot_create_file_path }}'
- device_id: !input notify_device
  enabled: !input enable_smartphone_notification
  domain: mobile_app
  type: notify
  title: '{{ notification_title }}'
  message: '{{ notification_message }}'
  data: '{% set android_data = {"ttl":0,"priority":"high","channel":"doorbell","image":
    "%s"} | format(snapshot_access_file_path) %} {% set ios_data = {"attachment":
    {"url": "%s", "content_type": "JPEG"}} | format(snapshot_access_file_path) %}
    {{ ios_data if is_ios else android_data }}'
